### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by rjwijnen** [sureshchahal/angular2-adal#37]
Since angular 4 is released, is it possible to make this lib also useable for angular 4?

**Comment by mjisaak** [comment]
It looks like the module is not compatible with AOT. Therefore `ng build --prod `will fail on Angular4. As a workaround you can use
`ng build --prod --aot false`

**Comment by rjwijnen** [comment]
I found out that when i remove everything from the package.json and place all the 'missing' parts in my root package.json everything works...

**Comment by harry671003** [comment]
+1

**Comment by ericivarsson** [comment]
I´m having the same problem. I solve it by removing ng2-adal\node_modules before running AOT builds.

**Comment by nelsonmorais** [comment]
I also have the same issue but I was able to workaround it by adding the "baseUrl": "node_modules", to the tsconfig.json file.
The problem seems to be the import (import {Http, Response, Headers, RequestOptionsArgs, RequestOptions, RequestMethod, URLSearchParams} from '@angular/http';) in the authHttp.service.ts file that is resolving to the @angular/http on the node_modules folder under the adal folder.
By setting the baseUrl to the node_modules on the root of the project the compile problem was solved, but I still have a problems at runtime :(
When I try to inject the AuthHttp I always get the error: **No provider for Http!** and I've already tried to change the authHttp.module.ts to import the HttpModule from @angular/http and add it to the imports section of the @NgModule, but I always get the same error.
I'm using WebPack v1.x I I guess that the AOT is not being used. 
Any suggestions?

**Comment by rjwijnen** [comment]
Just add all needed packages to your root package.json and then remove the node-modules from the ng2-adal folder inside the root node-modules folder. (Node-modules/ng2-adal/node-modules)

**Comment by nelsonmorais** [comment]
@rjwijnen It works! I wonder why the change in the tsconfig.json is not enough and doesn't work. I would expect that the end result is the same since it redirects the import resolution to the path specified in the baseUrl.

**Comment by jrwpatterson** [comment]
@rjwijnen if your using yarn I added the following in a yarnclean file ng2-adal?node_modules deletes them on the install

**Comment by nelsonmorais** [comment]
@rjwijnen Thanks! We're still using npm, but we took a similar aproach :)

**Comment by 4kochi** [comment]
We use the fork https://github.com/straach/ngx-adal which works fine for us.

**Comment by davidreher** [comment]
@rjwijnen: this repo now works with Angular4 :) if you use ng-cli you need to clone the repo, build it using `npm run gulp` and then link it since the npm package is not yet updated.

@sureshchahal: Please publish the Angular4 package, so no workaround is needed anymore.

BTW: Thanks for providing this easy to use lib :)

**Comment by sureshchahal** [comment]
Package published. Latest version 1.x.x will support angular4 and 0.3.1 is supporting angular 2.
